/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ApiSheetsRouteImport } from './routes/api/sheets'

const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSheetsRoute = ApiSheetsRouteImport.update({
  id: '/api/sheets',
  path: '/api/sheets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/albums': typeof AlbumsRoute
  '/api/sheets': typeof ApiSheetsRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/albums': typeof AlbumsRoute
  '/api/sheets': typeof ApiSheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/albums': typeof AlbumsRoute
  '/api/sheets': typeof ApiSheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/albums' | '/api/sheets'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/albums' | '/api/sheets'
  id: '__root__' | '/$' | '/albums' | '/api/sheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AlbumsRoute: typeof AlbumsRoute
  ApiSheetsRoute: typeof ApiSheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sheets': {
      id: '/api/sheets'
      path: '/api/sheets'
      fullPath: '/api/sheets'
      preLoaderRoute: typeof ApiSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AlbumsRoute: AlbumsRoute,
  ApiSheetsRoute: ApiSheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
